
services:
  backend:
    build: pdf_fuzz_back/
    container_name: pdf_fuzz_back
    ports:
      - "8000:8000"
  frontend:
    build: pdf_fuzz_front/
    container_name: pdf_fuzz_front
    ports:
      - "3000:80"
    environment:
      BACKEND_ADDRESS: backend
      BACKEND_PORT: "8000"
