
services:
  backend:
    build:
      context: pdf_fuzz_back/
    container_name: pdf_fuzz_back
    ports:
      - "8000:8000"
    environment:
      ELASTIC_ADDRESS: elastic
    volumes:
      - ./pdf_fuzz_back/:/app
    depends_on:
      elastic:
        condition: service_healthy

  frontend:
    build: pdf_fuzz_front/
    container_name: pdf_fuzz_front
    ports:
      - "3000:80"
    environment:
      BACKEND_ADDRESS: backend
      BACKEND_PORT: "8000"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elastic_search
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.license.self_generated.type: basic
    volumes:
    - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl  -s http://localhost:9200|grep -q 'for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  assets:
  es_data: